// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetParseCertificateDatesFromPEM(arg1) {
  return window['go']['main']['App']['GetParseCertificateDatesFromPEM'](arg1);
}

export function GetSSLCertificateExpiry(arg1) {
  return window['go']['main']['App']['GetSSLCertificateExpiry'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
